Repository openxrlab/xrfeitoria, pull requests merged in 2023-09, with the labels that each got.

#5 [Feature] Add more comprehensive error handling
  .github/CONTRIBUTING.md
  README.md
  docs/en/README.md
  docs/en/index.rst
  docs/en/src/Tutorials.rst
  pyproject.toml
  samples/README.md
  samples/run_all.py
  src/XRFeitoriaBpy/__init__.py
  src/XRFeitoriaUnreal/XRFeitoriaUnreal.uplugin
  tutorials/01_get_started.ipynb
  xrfeitoria/data_structure/constants.py
  xrfeitoria/utils/downloader.py
  xrfeitoria/utils/plugin_infos.json
  xrfeitoria/utils/runner.py
Labels: bug, enhancement

#7 [Feature] Polish tutorials & misc updates
  .gitignore
  docs/en/src/tutorials
  pyproject.toml
  samples/blender/03_basic_render.py
  samples/blender/04_staticmesh_render.py
  samples/blender/05_skeletalmesh_render.py
  src/XRFeitoriaBpy/core/factory.py
  src/XRFeitoriaBpy/properties.py
  src/XRFeitoriaUnreal/Content/Python/constants.py
  src/XRFeitoriaUnreal/Content/Python/custom_movie_pipeline.py
  src/XRFeitoriaUnreal/Content/Python/sequence.py
  src/XRFeitoriaUnreal/Content/Python/utils.py
  tests/blender/stress.py
  tests/setup.py
  tests/utils.py
  tutorials/01_get_started.ipynb
  tutorials/02_add_cameras.ipynb
  tutorials/02_randomization.ipynb
  tutorials/03_human_nerf.ipynb
  xrfeitoria/actor/actor_base.py
  xrfeitoria/actor/actor_blender.py
  xrfeitoria/actor/actor_unreal.py
  xrfeitoria/cmd/render.py
  xrfeitoria/data_structure/constants.py
  xrfeitoria/data_structure/models.py
  xrfeitoria/factory.py
  xrfeitoria/object/object_utils.py
  xrfeitoria/renderer/renderer_blender.py
  xrfeitoria/renderer/renderer_unreal.py
  xrfeitoria/sequence/sequence_base.py
  xrfeitoria/sequence/sequence_base.pyi
  xrfeitoria/sequence/sequence_blender.py
  xrfeitoria/sequence/sequence_blender.pyi
  xrfeitoria/sequence/sequence_unreal.py
  xrfeitoria/sequence/sequence_unreal.pyi
  xrfeitoria/sequence/sequence_wrapper.py
  xrfeitoria/sequence/sequence_wrapper.pyi
  xrfeitoria/utils/functions/blender_functions.py
  xrfeitoria/utils/functions/unreal_functions.py
  xrfeitoria/utils/reader.py
Labels: documentation, enhancement

#8 [Version] Bump version to v0.5.1
  README.md
  docs/en/apis/utils.rst
  docs/en/conf.py
  docs/en/index.rst
  docs/en/src/Tutorials.rst
  docs/en/src/cli.md
  docs/en/src/tutorials
  pyproject.toml
  samples/utils.py
  src/XRFeitoriaBpy/__init__.py
  src/XRFeitoriaUnreal/Content/Python/constants.py
  src/XRFeitoriaUnreal/Content/Python/sequence.py
  src/XRFeitoriaUnreal/Content/Python/utils.py
  src/XRFeitoriaUnreal/XRFeitoriaUnreal.uplugin
  tests/setup.py
  tests/utils.py
  tutorials/01_get_started.ipynb
  tutorials/02_randomization.ipynb
  tutorials/03_human_nerf.ipynb
  xrfeitoria/actor/actor_base.py
  xrfeitoria/cmd/render.py
  xrfeitoria/data_structure/constants.py
  xrfeitoria/data_structure/models.py
  xrfeitoria/sequence/sequence_base.py
  xrfeitoria/sequence/sequence_wrapper.py
  xrfeitoria/utils/functions/blender_functions.py
  xrfeitoria/utils/plugin_infos.json
  xrfeitoria/utils/publish_plugins.py
  xrfeitoria/utils/setup.py
  xrfeitoria/utils/viewer.py
Labels: bug, documentation
